camera0: 3
camera1: 1
frame_width: 1920
frame_height: 1080
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 1
checkerboard_box_size_scale : 2.35
checkerboard_rows: 6
checkerboard_columns: 9
cooldown: 30
